#!/bin/bash
cat cms/app.js | awk '
BEGIN { in_pdf_block = 0; }
/if \(btnExtractPdf && pdfUpload\) {/ {
    print "  const btnExtractCifrado = document.getElementById('\''btn-extract-cifrado'\'');";
    print "  const cifradoUpload = document.getElementById('\''cifrado-upload'\'');";
    print "";
    print "  async function processAiExtraction(file, modo) {";
    print "    if (!file) return;";
    print "    const formData = new FormData();";
    print "    formData.append('\''pdf'\'', file);";
    print "    formData.append('\''modo'\'', modo);";
    print "    ";
    print "    let plainLyrics = \"\";";
    print "    const sourceStanzas = state.activeDraft?.data?.estrofas || state.currentSong?.estrofas || [];";
    print "    plainLyrics = sourceStanzas.filter(s => s.idioma === state.currentCifraLang).map(s => s.texto).join(\"\\n\\n\");";
    print "    ";
    print "    formData.append('\''letras'\'', plainLyrics);";
    print "    formData.append('\''cancion_id'\'', state.currentSong ? state.currentSong.id : '\''temp'\'');";
    print "    ";
    print "    pdfExtractLoading.classList.remove('\''hidden'\'');";
    print "    pdfDiscrepanciesAlert.classList.add('\''hidden'\'');";
    print "    pdfDiscrepanciesList.innerHTML = '\'''\'';";
    print "    ";
    print "    try {";
    print "      const response = await fetch(`${API_BASE}/pdf-extract`, {";
    print "        method: '\''POST'\'',";
    print "        headers: { '\''Authorization'\'': `Bearer ${state.token}` },";
    print "        body: formData";
    print "      });";
    print "      ";
    print "      const data = await response.json();";
    print "      if (!response.ok) {";
    print "        let errorMsg = data.error || '\''Error al procesar archivo'\'';";
    print "        if (data.details) {";
    print "          try {";
    print "            const detailsObj = typeof data.details === '\''string'\'' ? JSON.parse(data.details) : data.details;";
    print "            if (detailsObj.error && detailsObj.error.code === 503) {";
    print "               errorMsg = '\''La inteligencia artificial está sobrecargada en este momento. Por favor, intenta de nuevo en unos minutos.'\'';";
    print "            } else if (detailsObj.error && detailsObj.error.code === 429) {";
    print "               errorMsg = '\''Límite de peticiones gratuitas alcanzado (máx. 20 por minuto). Por favor, espera 1 minuto y vuelve a intentarlo.'\'';";
    print "            } else if (detailsObj.error && detailsObj.error.message) {";
    print "               errorMsg += '\'': '\'' + detailsObj.error.message;";
    print "            }";
    print "          } catch(e) {}";
    print "        }";
    print "        throw new Error(errorMsg);";
    print "      }";
    print "      ";
    print "      document.getElementById('\''cifra-key'\'').value = data.tonalidad || '\'''\'';";
    print "      document.getElementById('\''cifra-bpm'\'').value = data.bpm || '\'''\'';";
    print "      document.getElementById('\''cifra-tiempo'\'').value = data.tiempo || '\'''\'';";
    print "      document.getElementById('\''cifra-ritmo'\'').value = data.ritmo || '\'''\'';";
    print "      document.getElementById('\''chordpro-textarea'\'').value = data.chordpro || '\'''\'';";
    print "      ";
    print "      if (modo === '\''partitura'\'' && data.pdf_url) {";
    print "        state.currentSong = state.currentSong || {};";
    print "        state.currentSong.partitura_url = data.pdf_url;";
    print "        if (state.activeDraft && state.activeDraft.data) {";
    print "           state.activeDraft.data.partitura_url = data.pdf_url;";
    print "        }";
    print "        btnViewPdf.classList.remove('\''hidden'\'');";
    print "        btnViewPdf.onclick = () => window.open(data.pdf_url, '\''_blank'\'');";
    print "      }";
    print "      ";
    print "      if (data.discrepancias && data.discrepancias.length > 0) {";
    print "        data.discrepancias.forEach(d => {";
    print "          const li = document.createElement('\''li'\'');";
    print "          li.textContent = d;";
    print "          pdfDiscrepanciesList.appendChild(li);";
    print "        });";
    print "        pdfDiscrepanciesAlert.classList.remove('\''hidden'\'');";
    print "        showToast('\''⚠️ Resultado NO confiable. Resuelve las diferencias.'\'', true);";
    print "      } else {";
    print "        showToast('\''Archivo procesado correctamente'\'', false);";
    print "      }";
    print "      ";
    print "      saveDraftSong();";
    print "    } catch (err) {";
    print "      showToast(err.message, true);";
    print "    } finally {";
    print "      pdfExtractLoading.classList.add('\''hidden'\'');";
    print "      if (pdfUpload) pdfUpload.value = '\'''\'';";
    print "      if (cifradoUpload) cifradoUpload.value = '\'''\'';";
    print "    }";
    print "  }";
    print "";
    print "  if (btnExtractPdf && pdfUpload) {";
    print "    btnExtractPdf.addEventListener('\''click'\'', () => pdfUpload.click());";
    print "    pdfUpload.addEventListener('\''change'\'', (e) => processAiExtraction(e.target.files[0], '\''partitura'\''));";
    print "  }";
    print "  if (btnExtractCifrado && cifradoUpload) {";
    print "    btnExtractCifrado.addEventListener('\''click'\'', () => cifradoUpload.click());";
    print "    cifradoUpload.addEventListener('\''change'\'', (e) => processAiExtraction(e.target.files[0], '\''cifrado'\''));";
    print "  }";
    print "  ";
    print "  document.addEventListener('\''paste'\'', (e) => {";
    print "    if (!document.getElementById('\''cifra-panel'\'').classList.contains('\''hidden'\'')) {";
    print "      const items = e.clipboardData.items;";
    print "      for (let i = 0; i < items.length; i++) {";
    print "        if (items[i].type.indexOf('\''image'\'') !== -1) {";
    print "          const file = items[i].getAsFile();";
    print "          processAiExtraction(file, '\''cifrado'\'');";
    print "          break;";
    print "        }";
    print "      }";
    print "    }";
    print "  });";
    print "";
    in_pdf_block = 1;
    next;
}
in_pdf_block && /  \/\/ Chord Builder Modal Event Listeners/ {
    in_pdf_block = 0;
    print $0;
    next;
}
!in_pdf_block { print $0; }
' > patch.js
